#!/bin/bash -e
#
# author: mdye@us.ibm.com
#

$SNAP/usr/horizon/bin/horizon-prestart $SNAP_DATA/

if [[ -d "$SNAP_DATA"/etc/default/horizon-env ]]; then
  . "$SNAP_DATA"/etc/default/horizon-env
else
  . "$SNAP"/etc/default/horizon-env
fi

if [[ -d "$SNAP_DATA"/etc/horizon/anax.json.tmpl ]]; then
  CFG_PATH="$SNAP_DATA"/etc/horizon/anax.json.tmpl
else
  CFG_PATH="$SNAP"/etc/horizon/anax.json.tmpl
fi

envsubst <$(cat "$CFG_PATH") > "$SNAP_DATA"/etc/horizon/anax.json

"$SNAP"/usr/horizon/bin/anax -v "$ANAX_LOG_LEVEL" -logtostderr -config "$SNAP_DATA"/etc/horizon/anax.json
