#!/bin/bash -e
#
# author: mdye@us.ibm.com
#

function override() {
  if [ -e "${SNAP_COMMON}/$1" ]; then
    echo "${SNAP_COMMON}/$1"
  else
    echo "${SNAP}/$1"
  fi
}

# N.B. The order of the following is important: the prestart may want to adjust
# values in the file before sourcing
mkdir -p "$SNAP_COMMON"/etc/default
envsubst < $(override "etc/default/horizon.tmpl") > "$SNAP_COMMON"/etc/default/horizon
$(override "usr/horizon/sbin/horizon-prestart") $SNAP_COMMON "EPHEMERAL_ONLY"

set -o allexport
. "$SNAP_COMMON"/etc/default/horizon

envsubst < $(override "etc/horizon/anax.json.tmpl") > "$SNAP_COMMON"/etc/horizon/anax.json
"$SNAP"/usr/horizon/bin/anax -v "$ANAX_LOG_LEVEL" -logtostderr -config "$SNAP_COMMON"/etc/horizon/anax.json
