FROM ubuntu:16.10
MAINTAINER mdye <mdye@us.ibm.com>

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
      build-essential \
      devscripts \
      debhelper \
      dh-systemd \
      golang-1.7-go \
      npm \
      git \
      gnupg \
      vim \
      jq \
      curl \
      tree \
      wget \
      snapcraft
RUN ln -s /usr/lib/go-1.7/bin/go* /usr/bin/
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm install -g npm-cache
ARG CACHE_DATE=1977-06-27_15:17:32
RUN git clone https://github.com/open-horizon/horizon-pkg.git /horizon-pkg
WORKDIR /horizon-pkg
