FROM armv7/armhf-ubuntu:16.10
MAINTAINER mdye <mdye@us.ibm.com>

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
      build-essential \
      devscripts \
      debhelper \
      dh-systemd \
      golang-1.7-go \
      npm \
      git \
      gnupg \
      vim \
      jq \
      tree \
      snapcraft
RUN ln -s /usr/lib/go-1.7/bin/go* /usr/bin/
RUN mkdir /prj
WORKDIR /prj
