FROM arm64v8/ubuntu:16.04
MAINTAINER mdye <mdye@us.ibm.com>

ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt-get install -y \
      build-essential \
      devscripts \
      debhelper \
      dh-systemd \
      npm \
      git \
      gnupg \
      vim \
      jq \
      curl \
      tree \
      wget \
      gettext \
      snapcraft
RUN curl -s https://storage.googleapis.com/golang/go1.8.3.linux-armv6l.tar.gz | tar zxvf - -C /usr/local
RUN ln -s /usr/local/go/bin/go* /usr/bin/
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN npm install -g npm-cache
ARG CACHE_DATE=1977-06-27_15:17:32
RUN git clone https://github.com/open-horizon/horizon-deb-packager.git /horizon-deb-packager
WORKDIR /horizon-deb-packager
