#!/bin/bash

usage="Usage: $0 distribution_release version_prefix version_suffix destination_changelog original_changelog changelogfiles..."

if [[ $# -lt 6 ]]; then
  (>&2 echo "Missing required argument(s). $usage")
  exit 1
fi

distribution_release=$1
version_prefix=$2
version_suffix=$3
destination_changelog=$4
original_changelog=$5

gen_content=$(awk '{if (FNR == 1) printf("\n%-4s* %s\n"," ",$0); else printf("%-6s- %s\n"," ",$0);};' $(echo ${@:6}))

cat <<EOF > $destination_changelog
horizon (${version_prefix}${version_suffix}) $distribution_release; urgency=medium
${gen_content}

 -- Blue Horizon Team <developers@bluehorizon.network>  $(date -R)

$(cat $original_changelog)

EOF

